In [10]:
import pandas as pd
from datetime import date

In [13]:
df = pd.read_csv("../data/raw/data.csv", index_col=0)
df.head()

,Movie Name,Year of Release,Run Time in minutes,Movie Rating,Votes,MetaScore,Gross,Genre,Certification,Director,Stars,Description
0,The Shawshank Redemption,1994,142,9.3,2804443,82.0,28340000.0,['Drama'],R,['Frank Darabont'],"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'...","['Over', 'the', 'course', 'of', 'several', 'ye..."
1,The Godfather,1972,175,9.2,1954174,100.0,134970000.0,"['Crime', ' Drama']",R,['Francis Ford Coppola'],"['Marlon Brando', 'Al Pacino', 'James Caan', '...","['Don', 'Vito', 'Corleone,', 'head', 'of', 'a'..."
2,Ramayana: The Legend of Prince Rama,1993,135,9.2,12995,NaN,NaN,"['Animation', ' Action', ' Adventure']",PG,"['Ram Mohan', 'Yûgô Sakô', 'Koichi Saski']","['Arun Govil', 'Nikhil Kapoor', 'Edie Mirman',...","['An', 'anime', 'adaptation', 'of', 'the', 'Hi..."
3,The Chaos Class,1975,87,9.2,42231,NaN,NaN,"['Comedy', ' Drama']",NaN,['Ertem Egilmez'],"['Kemal Sunal', 'Münir Özkul', 'Halit Akçatepe...","['Lazy,', 'uneducated', 'students', 'share', '..."
4,The Dark Knight,2008,152,9.0,2786129,84.0,534860000.0,"['Action', ' Crime', ' Drama']",PG-13,['Christopher Nolan'],"['Christian Bale', 'Heath Ledger', 'Aaron Eckh...","['When', 'the', 'menace', 'known', 'as', 'the'..."

In [14]:
df.shape

(10000, 12)

In [17]:
df.dtypes

Movie Name                 str
Year of Release          int64
Run Time in minutes      int64
Movie Rating           float64
Votes                    int64
MetaScore              float64
Gross                  float64
Genre                      str
Certification              str
Director                   str
Stars                      str
Description                str
dtype: object

In [18]:
df.isnull().sum()

Movie Name                0
Year of Release           0
Run Time in minutes       0
Movie Rating              0
Votes                     0
MetaScore              2026
Gross                  2915
Genre                     0
Certification           369
Director                  0
Stars                     0
Description               0
dtype: int64

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Movie Name           10000 non-null  str
 1   Year of Release      10000 non-null  int64
 2   Run Time in minutes  10000 non-null  int64
 3   Movie Rating         10000 non-null  float64
 4   Votes                10000 non-null  int64
 5   MetaScore            7974 non-null   float64
 6   Gross                7085 non-null   float64
 7   Genre                10000 non-null  str
 8   Certification        9631 non-null   str
 9   Director             10000 non-null  str
 10  Stars                10000 non-null  str
 11  Description          10000 non-null  str
dtypes: float64(3), int64(3), str(6)
memory usage: 937.6 KB

In [20]:
df.describe()

,Year of Release,Run Time in minutes,Movie Rating,Votes,MetaScore,Gross
count,10000.000000,10000.000000,10000.000000,1.000000e+04,7974.000000,7.085000e+03
mean,2001.413600,110.725000,6.727020,9.279738e+04,59.171432,4.017500e+07
std,18.597804,22.053073,0.821264,1.716509e+05,17.268795,6.748658e+07
min,1915.000000,45.000000,4.900000,1.000200e+04,7.000000,0.000000e+00
25%,1994.000000,96.000000,6.100000,1.685175e+04,47.000000,2.340000e+06
50%,2007.000000,107.000000,6.700000,3.417950e+04,60.000000,1.693000e+07
75%,2015.000000,121.000000,7.300000,9.154600e+04,72.000000,4.864000e+07
max,2023.000000,439.000000,9.300000,2.804443e+06,100.000000,9.366600e+08

In [23]:
decadas = df.groupby((df["Year of Release"] // 10) * 10)

for ano, grupo in decadas:
    print(f"\nDécada {ano} - {ano+9}: {len(grupo)} filmes")
    print(grupo[["Movie Name", "Year of Release", "Movie Rating"]].to_string(index=False))

Década 1910 - 1919: 3 filmes
                                    Movie Name  Year of Release  Movie Rating
                                   Intolerance             1916           7.7
Broken Blossoms or the Yellow Man and the Girl             1919           7.2
                         The Birth of a Nation             1915           6.2

Década 1920 - 1929: 27 filmes
                           Movie Name  Year of Release  Movie Rating
                           Metropolis             1927           8.3
                              The Kid             1921           8.2
                         Sherlock Jr.             1924           8.2
                         Safety Last!             1923           8.1
                              Sunrise             1927           8.1
                          The General             1926           8.1
           The Passion of Joan of Arc             1928           8.1
                        The Gold Rush             1925           8.1
                                Faust             1926           8.1
                           The Circus             1928           8.1
          The Cabinet of Dr. Caligari             1920           8.0
                                Greed             1924           8.0
                 The Phantom Carriage             1921           8.0
                       The Last Laugh             1924           8.0
                        The Cameraman             1928           8.0
                            Nosferatu             1922           7.9
                  Battleship Potemkin             1925           7.9
                        Pandora's Box             1929           7.8
                        Seven Chances             1925           7.8
                      Our Hospitality             1923           7.8
                  Steamboat Bill, Jr.             1928           7.8
                                Wings             1927           7.6
                        The Navigator             1924           7.6
             The Phantom of the Opera             1925           7.5
The Lodger: A Story of the London Fog             1927           7.3
                            Blackmail             1929           6.9
                      The Jazz Singer             1927           6.4

Década 1930 - 1939: 83 filmes
                       Movie Name  Year of Release  Movie Rating
                     Modern Times             1936           8.5
                      City Lights             1931           8.5
                                M             1931           8.3
               Gone with the Wind             1939           8.2
I Am a Fugitive from a Chain Gang             1932           8.2
                 The Wizard of Oz             1939           8.1
     Mr. Smith Goes to Washington             1939           8.1
            It Happened One Night             1934           8.1
   All Quiet on the Western Front             1930           8.1
               The Grand Illusion             1937           8.1
                        King Kong             1933           7.9
     The Adventures of Robin Hood             1938           7.9
                   My Man Godfrey             1936           7.9
                     The Thin Man             1934           7.9
              Captains Courageous             1937           7.9
          Angels with Dirty Faces             1938           7.9
               Goodbye, Mr. Chips             1939           7.9
            The Rules of the Game             1939           7.9
             The Roaring Twenties             1939           7.9
              Trouble in Paradise             1932           7.9
      The Testament of Dr. Mabuse             1933           7.9
                           Freaks             1932           7.8
             A Night at the Opera             1935           7.8
                     Frankenstein             1931           7.8
        The Bride of Frankenstein             1935           7.8
                       Stagecoach             1939           7.8
                       L'Atalante             1934           7.8
                 Bringing Up Baby             1938           7.8
                  His Girl Friday             1939           7.8
                        Duck Soup             1933           7.8
      The Hunchback of Notre Dame             1939           7.8
       You Can't Take It with You             1938           7.8
                        Ninotchka             1939           7.8
           Mr. Deeds Goes to Town             1936           7.8
                             Fury             1936           7.8
                The Lady Vanishes             1938           7.7
                         Scarface             1932           7.7
                        The Women             1939           7.7
                          Holiday             1938           7.7
                    Captain Blood             1935           7.7
                  Der blaue Engel             1930           7.7
                          Top Hat             1935           7.7
                  The Awful Truth             1937           7.7
  Snow White and the Seven Dwarfs             1937           7.6
                The Invisible Man             1933           7.6
                     The 39 Steps             1935           7.6
                     Lost Horizon             1937           7.6
          Dr. Jekyll and Mr. Hyde             1931           7.6
                 The Public Enemy             1931           7.6
             Mutiny on the Bounty             1935           7.6
           Only Angels Have Wings             1939           7.6
               Destry Rides Again             1939           7.6
               After the Thin Man             1936           7.6
             The Petrified Forest             1936           7.5
               A Day at the Races             1937           7.5
                Wuthering Heights             1939           7.5
                   Horse Feathers             1932           7.5
                       Swing Time             1936           7.5
                 Alexander Nevsky             1938           7.5
                          Dracula             1931           7.4
                           Vampyr             1932           7.4
             Island of Lost Souls             1932           7.4
    The Hound of the Baskervilles             1939           7.4
                          Jezebel             1938           7.4
                     Dark Victory             1939           7.4
                  Animal Crackers             1930           7.4
                  Monkey Business             1931           7.4
                      Grand Hotel             1932           7.3
                   A Star Is Born             1937           7.3
                      42nd Street             1933           7.3
                    Little Caesar             1931           7.2
                        Gunga Din             1939           7.2
                       L'Age d'Or             1930           7.2
              Son of Frankenstein             1939           7.1
          The Most Dangerous Game             1932           7.1
                        The Mummy             1932           7.0
               The Old Dark House             1932           7.0
                         Sabotage             1936           7.0
                    The Black Cat             1934           6.9
               Young and Innocent             1937           6.8
        The Man Who Knew Too Much             1934           6.7
                      Jamaica Inn             1939           6.3
                     White Zombie             1932           6.2

Década 1940 - 1949: 137 filmes
                            Movie Name  Year of Release  Movie Rating
                 It's a Wonderful Life             1946           8.6
                            Casablanca             1942           8.5
                    The Great Dictator             1940           8.4
                          Citizen Kane             1941           8.3
                      Double Indemnity             1944           8.3
                       Bicycle Thieves             1948           8.3
                  Children of Paradise             1945           8.3
      The Treasure of the Sierra Madre             1948           8.2
                    To Be or Not to Be             1942           8.2
                           Late Spring             1949           8.2
                         The Third Man             1949           8.1
                               Rebecca             1940           8.1
                   The Grapes of Wrath             1940           8.1
           The Best Years of Our Lives             1946           8.1
                         The Red Shoes             1948           8.1
                            White Heat             1949           8.1
                           The Heiress             1949           8.1
                          Day of Wrath             1943           8.1
            The Shop Around the Corner             1940           8.0
                    The Maltese Falcon             1941           8.0
                       Brief Encounter             1945           8.0
                       Out of the Past             1947           8.0
                    Stairway to Heaven             1946           8.0
              Kind Hearts and Coronets             1949           8.0
                       Rome, Open City             1945           8.0
   The Life and Death of Colonel Blimp             1943           8.0
                   The Ox-Bow Incident             1943           8.0
                             Notorious             1946           7.9
                                  Rope             1948           7.9
                The Philadelphia Story             1940           7.9
                  Arsenic and Old Lace             1944           7.9
                         The Big Sleep             1946           7.9
                                 Laura             1944           7.9
                        Mildred Pierce             1945           7.9
                Miracle on 34th Street             1947           7.9
                  Beauty and the Beast             1946           7.9
                      The Lost Weekend             1945           7.9
                          Now, Voyager             1942           7.9
                    Sullivan's Travels             1941           7.9
          Letter from an Unknown Woman             1948           7.9
                      The Little Foxes             1941           7.9
                    Great Expectations             1946           7.8
                              Gaslight             1944           7.8
                          Oliver Twist             1948           7.8
                     Shadow of a Doubt             1943           7.8
                  To Have and Have Not             1944           7.8
                             Red River             1948           7.8
               The Ghost and Mrs. Muir             1947           7.8
                             Stray Dog             1949           7.8
                      Monsieur Verdoux             1947           7.8
                     Germany Year Zero             1948           7.8
                            Le Corbeau             1943           7.8
                              Fantasia             1940           7.7
                       Black Narcissus             1947           7.7
                        Scarlet Street             1945           7.7
                           The Killers             1946           7.7
                             Key Largo             1948           7.7
                 My Darling Clementine             1946           7.7
               How Green Was My Valley             1941           7.7
                   Twelve O'Clock High             1949           7.7
                       Nightmare Alley             1947           7.7
                         Sergeant York             1941           7.7
                          The Lady Eve             1941           7.7
                          Ball of Fire             1941           7.7
                       Waterloo Bridge             1940           7.7
               A Letter to Three Wives             1949           7.7
             Ivan the Terrible, Part I             1944           7.7
                   Leave Her to Heaven             1945           7.6
                                 Gilda             1946           7.6
                          Mrs. Miniver             1942           7.6
                              Lifeboat             1944           7.6
                        The Naked City             1948           7.6
             The Magnificent Ambersons             1942           7.6
                     The Bishop's Wife             1947           7.6
               The Woman in the Window             1944           7.6
                                Hamlet             1948           7.6
                           Brute Force             1947           7.6
                   Yankee Doodle Dandy             1942           7.6
                          The Sea Hawk             1940           7.6
                           Odd Man Out             1947           7.6
                         Meet John Doe             1941           7.6
              The Pride of the Yankees             1942           7.6
                         Drunken Angel             1948           7.6
                             Pinocchio             1940           7.5
                           High Sierra             1940           7.5
                            Spellbound             1945           7.5
                  Meet Me in St. Louis             1944           7.5
                The Lady from Shanghai             1947           7.5
            The Picture of Dorian Gray             1945           7.5
                         Dead of Night             1945           7.5
                          Dark Passage             1947           7.5
                     The Mark of Zorro             1940           7.5
                      Murder, My Sweet             1944           7.5
                            The Letter             1940           7.5
                  The Palm Beach Story             1942           7.5
        The Postman Always Rings Twice             1946           7.4
              And Then There Were None             1945           7.4
                 Foreign Correspondent             1940           7.4
                   The Thief of Bagdad             1940           7.4
                       Heaven Can Wait             1943           7.4
                           Fort Apache             1948           7.4
                    All the King's Men             1949           7.4
                     This Gun for Hire             1942           7.4
      The Strange Love of Martha Ivers             1946           7.4
                            Adam's Rib             1949           7.4
 Abbott and Costello Meet Frankenstein             1948           7.3
                                 Bambi             1942           7.3
                             Suspicion             1941           7.3
                          The Stranger             1946           7.3
                                Detour             1945           7.3
                           Holiday Inn             1942           7.3
                           On the Town             1949           7.3
                  The Spiral Staircase             1946           7.3
              Christmas in Connecticut             1945           7.3
                   Sorry, Wrong Number             1948           7.3
                         Easter Parade             1948           7.3
                      My Favorite Wife             1940           7.3
                          The Wolf Man             1941           7.2
                                 Dumbo             1941           7.2
                            Cat People             1942           7.2
                         The Uninvited             1944           7.2
                 Gentleman's Agreement             1947           7.2
              She Wore a Yellow Ribbon             1949           7.2
                                D.O.A.             1949           7.2
  Mr. Blandings Builds His Dream House             1948           7.2
                              Saboteur             1942           7.1
                     Woman of the Year             1942           7.1
                          Going My Way             1944           7.0
                      The Fountainhead             1949           7.0
                     Sands of Iwo Jima             1949           7.0
                I Walked with a Zombie             1943           7.0
                          3 Godfathers             1948           7.0
                     Song of the South             1946           6.9
The Adventures of Ichabod and Mr. Toad             1949           6.9
                     The Paradine Case             1947           6.5
                  The Three Caballeros             1944           6.3
                      Mr. & Mrs. Smith             1941           6.3

Década 1950 - 1959: 212 filmes
                        Movie Name  Year of Release  Movie Rating
                      12 Angry Men             1957           9.0
                     Seven Samurai             1954           8.6
                       Rear Window             1954           8.5
                  The World of Apu             1959           8.5
                      Sunset Blvd.             1950           8.4
                    Paths of Glory             1957           8.4
       Witness for the Prosecution             1957           8.4
                Sansho the Bailiff             1954           8.4
                           Vertigo             1958           8.3
               Singin' in the Rain             1952           8.3
                North by Northwest             1959           8.3
                             Ikiru             1952           8.3
          The Young and the Damned             1950           8.3
             The Cranes Are Flying             1957           8.3
                             Ordet             1955           8.3
                  Some Like It Hot             1959           8.2
                     All About Eve             1950           8.2
                 Dial M for Murder             1954           8.2
                          Rashomon             1950           8.2
                 The Wages of Fear             1953           8.2
                   Pather Panchali             1955           8.2
               A Face in the Crowd             1957           8.2
                            Ugetsu             1953           8.2
                     A Man Escaped             1956           8.2
                        Umberto D.             1952           8.2
                         Aparajito             1956           8.2
               Ballad of a Soldier             1959           8.2
                           Ben-Hur             1959           8.1
                  The Seventh Seal             1957           8.1
                 On the Waterfront             1954           8.1
      The Bridge on the River Kwai             1957           8.1
                       Tokyo Story             1953           8.1
                     The 400 Blows             1959           8.1
                 Wild Strawberries             1957           8.1
                        Diabolique             1955           8.1
               The Hidden Fortress             1958           8.1